# Generated by Django 5.0.6 on 2024-05-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='academicLevel',
            field=models.CharField(blank=True, choices=[('Senior High School', 'Senior High School'), ('Undergraduate', 'Undergraduate'), ('Master', 'Master'), ('Doctorate', 'Doctorate'), ('Employee', 'Employee')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='learningType',
            field=models.CharField(blank=True, choices=[('Visual Learner', 'Visual Learner'), ('Read/Write Learner', 'Read/Write Learner'), ('Auditory Learner', 'Auditory Learner'), ('Kinsethetic Learner', 'Kinesthetic Learner'), ('Solitary Learner', 'Solitary Learner'), ('Naturalistic Learner', 'Naturalistic Learner'), ('Social Learner', 'Social Learner')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='studyPlace',
            field=models.CharField(blank=True, choices=[('Cafe', 'Cafe'), ('Library', 'Library'), ('Park', 'Park'), ('Video Call', 'Video Call'), ('Call', 'Call')], max_length=100, null=True),
        ),
    ]
