# Generated by Django 5.0.6 on 2024-06-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0003_preference_matkul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='matkul',
        ),
    ]
