# Generated by Django 5.0.6 on 2024-06-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0004_remove_preference_matkul'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='matkul',
            field=models.CharField(blank=True, choices=[('Math', 'Math'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Literature', 'Literature'), ('Coding', 'Coding'), ('Law', 'Law'), ('Accounting', 'Accounting')], max_length=10, null=True),
        ),
    ]
