# Generated by Django 5.0.6 on 2024-06-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0005_preference_matkul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
