# Generated by Django 5.0.6 on 2024-06-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0006_alter_preference_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='age',
        ),
    ]
