# Generated by Django 5.0.6 on 2024-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0007_remove_preference_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='role',
            field=models.CharField(blank=True, choices=[('A Study Mate', 'A Study Mate'), ('Someone to Teach', 'Someone to Teach'), ('Someone to Learn', 'Someone to Learn')], max_length=100, null=True),
        ),
    ]
