# Generated by Django 5.0.6 on 2024-06-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0009_alter_preference_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='learningType',
            field=models.CharField(blank=True, choices=[('Visual Learner', 'Visual Learner'), ('Read/Write Learner', 'Read/Write Learner'), ('Auditory Learner', 'Auditory Learner'), ('Kinesthetic Learner', 'Kinesthetic Learner'), ('Solitary Learner', 'Solitary Learner'), ('Naturalistic Learner', 'Naturalistic Learner'), ('Social Learner', 'Social Learner')], max_length=100, null=True),
        ),
    ]
