# Generated by Django 5.0.6 on 2024-05-23 07:58

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_userprofile_academiclevel_userprofile_learningtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=Profile.models.UserProfile.user_profilepicture_path),
        ),
    ]
