# Generated by Django 5.0.6 on 2024-05-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
