# Generated by Django 5.0.6 on 2024-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_remove_userprofile_user_userprofile_last_login'),
        ('filter', '0001_initial'),
        ('preference', '0002_preference_academiclevel_preference_learningtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.ManyToManyField(through='filter.UserPreference', to='preference.preference'),
        ),
    ]
