# Generated by Django 5.0.6 on 2024-05-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_userprofile_preferences'),
        ('interest', '0001_initial'),
        ('userInterest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest',
            field=models.ManyToManyField(through='userInterest.UserInterest', to='interest.matkul'),
        ),
    ]
