# Generated by Django 5.0.6 on 2024-05-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_userprofile_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
