# Generated by Django 5.0.6 on 2024-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_remove_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matkul',
            field=models.CharField(blank=True, choices=[('Math', 'Math'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Literature', 'Literature'), ('Coding', 'Coding'), ('Law', 'Law'), ('Accounting', 'Accounting')], max_length=10, null=True),
        ),
    ]
