# Generated by Django 5.0.6 on 2024-06-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_alter_userprofile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('A Study Mate', 'A Study Mate'), ('Someone to Teach', 'Someone to Teach'), ('Someone to Learn', 'Someone to Teach')], max_length=100, null=True),
        ),
    ]
