# Generated by Django 5.0.3 on 2024-04-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('A Study Mate', 'A Study Mate'), ('Someone to Teach', 'Someone to Teach'), ('Someone to Learn', 'Someone to Teach')], default='A Study Mate', max_length=100),
        ),
    ]
