# Generated by Django 5.0.3 on 2024-04-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul', models.CharField(choices=[('Math', 'Math'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Literature', 'Literature'), ('Coding', 'Coding'), ('Law', 'Law'), ('Accounting', 'Accounting')], max_length=10)),
            ],
        ),
    ]
