# Generated by Django 5.0.3 on 2024-04-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0002_userinterest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
